/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "ChatbotWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Images": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MongoUri": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}